version: "3.7"
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8089:8080
volumes:
  db-data:
  test-db-data:
