[project]
name = "flask-playground-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Davide Pugliese", email = "deviad@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic>=2.11.7",
    "sqlalchemy>=2.0.41",
    "typing>=3.10.0.0",
    "typing-extensions>=4.14.1",
]

[project.scripts]
flask-playground-poc = "flask_playground_poc:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
